### PR TITLE
Update gnucashbook.py

### PR DESCRIPTION
**Pull request by sisihagen**
https://stackoverflow.com/questions/3195405/attributeerror-datetime-date-object-has-no-attribute-date

This will close the issue.

### CODE REVIEW

**Comment by partizand** [comment]
It is not right. This line does nothing.
It is necessary to remove time from the datetime
In my tested versions X is numpy datetime type with function date()

You may simply comment this lines.

**Comment by sisihagen** [comment]
By me change it to the follow output:

`gcreport ~/.finance/siefkesilvio.gnucash ~/Downloads/reort.xlsx
Opening file /home/siefke/.finance/siefkesilvio.gnucash ...
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid bf0898be408f4c183dd53098e43f2df7
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 02fa3f955a397cb14675c73690512255
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 2ea397f877623ef3ffee2f6257083fb0
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 74a334ab71ea507a56c3c99e6dff190a
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 848371c6af381ef8a6424821a7d64fb3
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 806bb014dea1623f5b527a464d8dfe8d
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid fd174087398ac782d30905e54031137b
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 1c86e80fdc73715916f4307d90bca9b1
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid c3d05daef6e8ad56ae4e4f210e3baf59
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 85323ed69c4f0dcdab5f84097aa9c85f
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid bf84b0b596ce674d66c54fa2cfa6f829
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 10ef8f970b2d7bf6e0a716b429aa4ae7
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 569dd203beb6235626721e53d5bd376e
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 9f2689a257a97e2670969f2e87570149
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid c377f68357fd9b88d41ccf0ebc0b9215
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 25b8f5aba4504f1adf26692a0ee23b01
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 726fdf84a697e7fd52e919e2d174ed81
Unknown multi transaction type for xirr. Transaction_guid da7b2d9927eb48f781553da25a344073
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 62693bffa821016d8c865b1005dd818a
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 539bca00be629ed60ceb9c0f123eb27b
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 9d2bec7e44ad43e7bc9cb5c13c9b31cd
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid ae91fd0a2a8fb679dbd87082fab20038
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 7a1e87a4266163c8e7bf835f0fd22877
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid dcb2cefe07dbf290547f24539915297c
Unknown multi transaction type for xirr. Transaction_guid 1fb8736d44840e76b2cad45d89e28fe9
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid cddf183adaaf7b209b47f7dee666635f
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 03092cc1d3791de628567a8b32b5017d
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid d99ab3b22b7e1bd52a0cf6f1e4b00bc0
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 3662c587973d02e825cc241c9ee0cdb6
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid d7e72011207e6c529c6b5c9f2faa964c
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 16022cae95bfa55576b9918dd88c3547
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid c79fa1aa20802b39acbc12a160c0cc12
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 461b821b49309206d3501a647067fe3b
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 21d57c1dd4278ef468ec6699a57792eb

Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 900c4c83977c2b3f6afde47bce8ba2f7

Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 936114a38aa07145cfc999a71a8a756c
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid b9593c797d84b9c8922b4d68306e1355
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid e5fd746cb797ad399b4f185c65cb29c4
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 0496f948f8d267e88f4d8658cc702505
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 396fb1ca77828026ccd71fad91660ab2
Building reports into /home/siefke/Downloads/reort.xlsx ...

Traceback (most recent call last):
  File "/home/siefke/.python/bin/gcreport", line 11, in <module> sys.exit(main())
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport/gcreportcli.py", line 32, in main
    gcrep.all_reports_excel(p_args.xlsx_file, glevel=p_args.glevel)
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport/gcreport.py", line 101, in all_reports_excel
    self._complex_report_writer(xlsxreport, start_date, end_date, period='M', glevel=glevel)
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport/gcreport.py", line 240, in _complex_report_writer
    glevel=glevel)
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport/gnucashdata.py", line 1410, in turnover_by_period
    account_type=account_type)
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport/gnucashdata.py", line 1518, in _turnover_group_by_period
    sel_df = self.df_splits[(self.df_splits[cols.POST_DATE] >= from_date)
  File "/home/siefke/.python/lib/python3.6/site-packages/pandas/core/ops.py", line 1201, in wrapper
    pd.DatetimeIndex)
  File "/home/siefke/.python/lib/python3.6/site-packages/pandas/core/ops.py", line 1098, in dispatch_to_index_op
    result = op(left_idx, right)
  File "/home/siefke/.python/lib/python3.6/site-packages/pandas/core/indexes/datetimes.py", line 133, in wrapper
    (type(other), str(other)))
TypeError: <class 'datetime.date'> type object 1997-10-01
`

But at end maybe not work on Linux. Linux and Windows is different in date handle? 

Silvio

**Comment by partizand** [comment]
I think that the date type is not correct in transactions. Because of this problem.
Ideally I need your * .gnucash file. But it's private. Can you send at least a template with several transactions?

**Comment by sisihagen** [comment]
Hello, 

I have a file upload maybe help when data not enough I can clone more input if it will help you. 

Silvio 

https://github.com/sisihagen/testfiles

**Comment by partizand** [comment]
Thank`s. All data transactions is 01.01.1970. Is it right?

**Comment by sisihagen** [comment]
No all from 2017 is first one 2018 the other. You see 1970? That's crazy. Maybe is local that's why? I change now date format to ISO, maybe help it more?

Silvio

**Comment by partizand** [comment]
I found the reason. I have a date like this 19700101000000. You have 1970-01-01 00:00:00. There is no type recognition to datetime type and errors appear.
I need to add a type check.

What version of gnucash? Why it records dates in different ways ...

**Comment by sisihagen** [comment]
I use Version 3.1. I not know why is this. I have activate local date maybe this? If you go to settings, date and set it to iso maybe will help? Why I not know, should we ask for it on the gnucash mailling list. Should I open a thread there for it or will you do it? I be not really a coder.

**Comment by partizand** [comment]
Even the length of the date fields is different. 14 and 19 characters.
Yes, I see 1970.

**Comment by partizand** [comment]
I use 2.6.18 GnuCash. Changes in versions are possible. Now I'll try 3.1. wait...

**Comment by partizand** [comment]
Yes, in the new version the date is stored differently.
I will make changes and publish my program. But it will be necessary to wait.

**Comment by partizand** [comment]
Note that such errors mean that you can not calculate the yield on these transactions. This combination of split is not included in the program.
It will work, but the calculation will be incorrect

Transaction with multi stock accounts. Xirr rule not set. Transaction_guid cddf183adaaf7b209b47f7dee666635f
Transaction with multi stock accounts. Xirr rule not set. Transaction_guid 03092cc1d3791de628567a8b32b5017d

**Comment by partizand** [comment]
Please, try version 0.2.2
pip install --upgrade gnucashreport

tests on 3 version of GnuCash is ok

**Comment by sisihagen** [comment]
I have do and it crash with 

```
Opening file /home/siefke/.finance/siefkesilvio.gnucash ...
Traceback (most recent call last):
  File "/home/siefke/.python/bin/gcreport", line 11, in <module>
    sys.exit(main())
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport/gcreportcli.py", line 29, in main
    raw_data = RawData(p_args.gnucash_file)
NameError: name 'RawData' is not defined
```
Same result with new install.

**Comment by partizand** [comment]
Hurried up...
Updated the branch master
Download zip of last master branch, unpack. Enter to root directory (where setup.py)
Then install:
python setup.py install

This must install 0.2.3 version

And try again...

**Comment by sisihagen** [comment]
Hi, 

sorry for late message. I was on road today. So I have update and let run but it ends with tz problem. TZ Module is installed but it will not worked. 

```
(.python) [siefke@sisi-arch ~]$ gcreport ~/.finance/siefkesilvio.gnucash > sisif.xlsx
Traceback (most recent call last):
  File "/home/siefke/.python/bin/gcreport", line 11, in <module>
    load_entry_point('gnucashreport==0.2.3', 'console_scripts', 'gcreport')()
  File "/home/siefke/.python/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/siefke/.python/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/home/siefke/.python/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/home/siefke/.python/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport-0.2.3-py3.6.egg/gnucashreport/gcreportcli.py", line 10, in <module>
    from gnucashreport.buildreport import BuildReport
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport-0.2.3-py3.6.egg/gnucashreport/buildreport.py", line 1, in <module>
    from gnucashreport.gnucashbook import GNUCashBook
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport-0.2.3-py3.6.egg/gnucashreport/gnucashbook.py", line 9, in <module>
    from dateutil.parser import tz, parse as parse_date
ImportError: cannot import name 'tz'
(.python) [siefke@sisi-arch ~]$ pip install tz
Requirement already satisfied: tz in ./.python/lib/python3.6/site-packages (0.2.2)
(.python) [siefke@sisi-arch ~]$ gcreport ~/.finance/siefkesilvio.gnucash > sisif.xlsx
Traceback (most recent call last):
  File "/home/siefke/.python/bin/gcreport", line 11, in <module>
    load_entry_point('gnucashreport==0.2.3', 'console_scripts', 'gcreport')()
  File "/home/siefke/.python/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/siefke/.python/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/home/siefke/.python/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/home/siefke/.python/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport-0.2.3-py3.6.egg/gnucashreport/gcreportcli.py", line 10, in <module>
    from gnucashreport.buildreport import BuildReport
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport-0.2.3-py3.6.egg/gnucashreport/buildreport.py", line 1, in <module>
    from gnucashreport.gnucashbook import GNUCashBook
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport-0.2.3-py3.6.egg/gnucashreport/gnucashbook.py", line 9, in <module>
    from dateutil.parser import tz, parse as parse_date
ImportError: cannot import name 'tz'
```

I have try with EGG Cache so what I found on net but it will not work. 

https://stackoverflow.com/questions/4212240/importerror-cannot-import-name-tz-psycopg2?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa 

Maybe wrong Idea I be not sure. 

Silvio

**Comment by partizand** [comment]
Please, repeat download last master branch and install
python setup.py install

Version will not change, the file will change (gnucashbook.py)

In new dateutil library changed import tz...
instead: from dateutil.parser import tz
has become: from dateutil import tz

**Comment by sisihagen** [comment]
now we are at the start 

```
Opening file /home/siefke/.finance/siefkesilvio.gnucash ...
Building reports into sisi.xlsx ...
Traceback (most recent call last):
  File "/home/siefke/.python/bin/gcreport", line 11, in <module>
    load_entry_point('gnucashreport==0.2.3', 'console_scripts', 'gcreport')()
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport-0.2.3-py3.6.egg/gnucashreport/gcreportcli.py", line 54, in main
    build_cli_report(p_args.gnucash_file, p_args.xlsx_file, p_args.glevel)
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport-0.2.3-py3.6.egg/gnucashreport/gcreportcli.py", line 42, in build_cli_report
    reportset = builder.get_reportset_all(glevel=glevel)
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport-0.2.3-py3.6.egg/gnucashreport/buildreport.py", line 200, in get_reportset_all
    period='M', glevel=glevel)
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport-0.2.3-py3.6.egg/gnucashreport/buildreport.py", line 163, in get_reportset_complex
    report = self.get_report_income(from_date=from_date, to_date=to_date, period=period, glevel=glevel)
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport-0.2.3-py3.6.egg/gnucashreport/buildreport.py", line 65, in get_report_income
    account_type=GNUCashBook.INCOME, margins=margins, glevel=glevel)
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport-0.2.3-py3.6.egg/gnucashreport/rawdata.py", line 1452, in turnover_by_period
    account_type=account_type)
  File "/home/siefke/.python/lib/python3.6/site-packages/gnucashreport-0.2.3-py3.6.egg/gnucashreport/rawdata.py", line 1560, in _turnover_group_by_period
    sel_df = self.df_splits[(self.df_splits[cols.POST_DATE] >= from_date)
  File "/home/siefke/.python/lib/python3.6/site-packages/pandas/core/ops.py", line 1201, in wrapper
    pd.DatetimeIndex)
  File "/home/siefke/.python/lib/python3.6/site-packages/pandas/core/ops.py", line 1098, in dispatch_to_index_op
    result = op(left_idx, right)
  File "/home/siefke/.python/lib/python3.6/site-packages/pandas/core/indexes/datetimes.py", line 133, in wrapper
    (type(other), str(other)))
TypeError: <class 'datetime.date'> type object 1997-10-01
```

Maybe will not work? Im sorry can not help you. The software sounds great because I need really a chance to extract win and lost of every year. But this python stuff often make trouble. 

Silvio

**Comment by partizand** [comment]
I'm in a hurry.
Even if it works, there may be problems with the calculation of profitability. Transactions should be of a certain type. Judging by your warnings, they do not match.
Let me debug properly, not hurrying.
I abandoned this program, there is no time. I tried to launch the new version, but apparently I did not finish it.
I'll take the old one and rewrite only the dates.
In any case, thanks for the feedback.
I use it myself every month, so I'll finish it anyway.

**Comment by sisihagen** [comment]
No problem maybe one day will work one script. All python scripts here on github have same problems with date. So no one is alone :) The date in sqlite database is set correct in english format so I think Gnucash convert date in the software. 

Silvio 

PS: Nice weekend

**Comment by partizand** [comment]
Hi, Silvio

I published version 0.2.3
It works on my current base of gnucash

pip uninstall gnucashreport
pip install gnucashreport

It turns out I ran the tests on the old version ...
And the libraries that I use have changed their api

Maybe it will work :)

**Comment by partizand** [comment]
Fixed, use 0.2.3 version (works with GnuCash 3.1).
There's nobody to test. For me works

**Pull request closed without merging**
